/** All RBAC roles defined in the actor catalogue. */
export const ROLES = [
    'student',
    'module-tutor',
    'personal-tutor',
    'research-supervisor',
    'wellbeing-advisor',
    'wellbeing-mental-health-advisor',
    'wellbeing-panel-chair',
    'wellbeing-auditor',
    'exam-board-member',
    'exam-board-chair',
    'external-examiner',
    'integrity-officer',
    'registry-administrator',
    'regulatory-officer',
    'finance-administrator',
    'dpo',
    'tenant-administrator',
    'system-administrator',
    'integration-service',
];
/**
 * Permission → roles that hold it.
 * Application middleware checks these at route level.
 */
export const PERMISSION_ROLES = {
    'student:read:own': ['student'],
    'student:read:all': ['registry-administrator', 'exam-board-chair', 'wellbeing-advisor', 'dpo'],
    'student:write': ['registry-administrator'],
    'enrolment:read:own': ['student'],
    'enrolment:read:all': ['registry-administrator', 'exam-board-chair', 'wellbeing-advisor', 'finance-administrator'],
    'enrolment:write': ['registry-administrator'],
    'mark:read:own': ['student'],
    'mark:read:all': ['registry-administrator', 'module-tutor', 'exam-board-chair', 'exam-board-member'],
    'mark:write': ['registry-administrator', 'module-tutor', 'integration-service'],
    'exam-board:read': ['registry-administrator', 'exam-board-chair', 'exam-board-member', 'external-examiner'],
    'exam-board:ratify': ['exam-board-chair'],
    'adjustment:read:own': ['student'],
    'adjustment:read:all': ['registry-administrator', 'wellbeing-advisor', 'integration-service'],
    'adjustment:write': ['registry-administrator', 'wellbeing-advisor'],
    'special-category:read': ['wellbeing-advisor', 'wellbeing-mental-health-advisor', 'wellbeing-panel-chair', 'wellbeing-auditor', 'dpo', 'registry-administrator'],
    'mh-session-note:read': ['wellbeing-mental-health-advisor', 'wellbeing-auditor', 'dpo'],
    'panel-decision:write': ['wellbeing-panel-chair', 'registry-administrator'],
    'wellbeing-sar:export': ['wellbeing-auditor', 'dpo'],
    'wellbeing-retention:write': ['wellbeing-auditor', 'registry-administrator'],
    'config:write': ['tenant-administrator'],
    'integration:manage': ['tenant-administrator', 'integration-service'],
    'audit:read': ['dpo', 'system-administrator', 'wellbeing-auditor'],
    'tenant:manage': ['system-administrator'],
    'rule:read': ['registry-administrator', 'tenant-administrator'],
    'rule:write': ['tenant-administrator'],
    'module-registration:read:own': ['student'],
    'module-registration:read:all': ['registry-administrator', 'module-tutor', 'integration-service'],
    'module-registration:write': ['registry-administrator'],
    'catalogue:read': ['student', 'module-tutor', 'personal-tutor', 'registry-administrator', 'exam-board-member', 'exam-board-chair', 'integration-service'],
    'catalogue:write': ['registry-administrator', 'tenant-administrator'],
    'calendar:read': ['student', 'module-tutor', 'registry-administrator', 'integration-service'],
    'calendar:write': ['registry-administrator', 'tenant-administrator'],
    'disability:read': ['wellbeing-advisor', 'wellbeing-mental-health-advisor', 'wellbeing-panel-chair', 'wellbeing-auditor', 'dpo', 'registry-administrator'],
    'disability:write': ['wellbeing-advisor', 'wellbeing-mental-health-advisor', 'registry-administrator'],
    'exam-board:write': ['registry-administrator'],
    'circumstances:read': ['registry-administrator', 'wellbeing-advisor'],
    'circumstances:write': ['registry-administrator'],
    'progression:read': ['registry-administrator', 'exam-board-chair', 'exam-board-member'],
    'progression:write': ['registry-administrator'],
    'regulatory:read': ['registry-administrator', 'regulatory-officer'],
    'regulatory:write': ['registry-administrator', 'regulatory-officer'],
    'workflow:read': ['registry-administrator', 'tenant-administrator'],
    'workflow:write': ['tenant-administrator'],
    'workflow-task:complete': ['registry-administrator', 'module-tutor', 'personal-tutor', 'wellbeing-advisor', 'exam-board-member', 'exam-board-chair', 'regulatory-officer', 'finance-administrator', 'tenant-administrator'],
    'feature-flag:read': ['registry-administrator', 'tenant-administrator', 'system-administrator'],
    'feature-flag:write': ['tenant-administrator', 'system-administrator'],
    'feature-flag:govern': ['system-administrator'],
    'environment:read': ['registry-administrator', 'tenant-administrator'],
    'environment:write': ['tenant-administrator'],
    'globalisation:read': ['registry-administrator', 'tenant-administrator'],
    'globalisation:write': ['tenant-administrator'],
    'communications:read': ['registry-administrator', 'tenant-administrator'],
    'communications:write': ['registry-administrator', 'tenant-administrator'],
};
export function hasPermission(roles, permission) {
    const required = PERMISSION_ROLES[permission];
    return roles.some((r) => required.includes(r));
}
//# sourceMappingURL=permissions.js.map