/** All RBAC roles defined in the actor catalogue. */
export const ROLES = [
  'student',
  'module-tutor',
  'personal-tutor',
  'engagement-officer',
  'research-supervisor',
  'wellbeing-advisor',
  'wellbeing-mental-health-advisor',
  'wellbeing-panel-chair',
  'wellbeing-auditor',
  'exam-board-member',
  'exam-board-chair',
  'external-examiner',
  'integrity-officer',
  'registry-administrator',
  'regulatory-officer',
  'finance-administrator',
  'dpo',
  'tenant-administrator',
  'system-administrator',
  'integration-service',
] as const;

export type Role = (typeof ROLES)[number];

/**
 * Permission → roles that hold it.
 * Application middleware checks these at route level.
 */
export const PERMISSION_ROLES = {
  'student:read:own':          ['student'] as Role[],
  'student:read:all':          ['registry-administrator', 'exam-board-chair', 'wellbeing-advisor', 'dpo', 'external-examiner'] as Role[],
  'student:write':             ['registry-administrator'] as Role[],
  'enrolment:read:own':        ['student'] as Role[],
  'enrolment:read:all':        ['registry-administrator', 'exam-board-chair', 'wellbeing-advisor', 'finance-administrator', 'external-examiner'] as Role[],
  'enrolment:write':           ['registry-administrator'] as Role[],
  'mark:read:own':             ['student'] as Role[],
  'mark:read:all':             ['registry-administrator', 'module-tutor', 'exam-board-chair', 'exam-board-member', 'external-examiner'] as Role[],
  'mark:write':                ['registry-administrator', 'module-tutor', 'integration-service'] as Role[],
  'exam-board:read':           ['registry-administrator', 'exam-board-chair', 'exam-board-member', 'external-examiner'] as Role[],
  'exam-board:ratify':         ['exam-board-chair', 'registry-administrator'] as Role[],
  'adjustment:read:own':       ['student'] as Role[],
  'adjustment:read:all':       ['registry-administrator', 'wellbeing-advisor', 'integration-service'] as Role[],
  'adjustment:write':          ['registry-administrator', 'wellbeing-advisor'] as Role[],
  'special-category:read':     ['wellbeing-advisor', 'wellbeing-mental-health-advisor', 'wellbeing-panel-chair', 'wellbeing-auditor', 'dpo', 'registry-administrator'] as Role[],
  'mh-session-note:read':      ['wellbeing-mental-health-advisor', 'wellbeing-auditor', 'dpo'] as Role[],
  'panel-decision:write':      ['wellbeing-panel-chair', 'registry-administrator'] as Role[],
  'wellbeing-sar:export':      ['wellbeing-auditor', 'dpo'] as Role[],
  'wellbeing-retention:write': ['wellbeing-auditor', 'registry-administrator'] as Role[],
  'config:read':               ['registry-administrator', 'tenant-administrator', 'system-administrator'] as Role[],
  'config:write':              ['tenant-administrator'] as Role[],
  'integration:read':          ['registry-administrator', 'tenant-administrator', 'system-administrator', 'integration-service'] as Role[],
  'integration:manage':        ['tenant-administrator', 'integration-service'] as Role[],
  'audit:read':                ['dpo', 'system-administrator', 'wellbeing-auditor'] as Role[],
  'tenant:manage':             ['system-administrator'] as Role[],
  'rule:read':                          ['registry-administrator', 'tenant-administrator'] as Role[],
  'rule:write':                         ['tenant-administrator'] as Role[],
  'module-registration:read:own':       ['student'] as Role[],
  'module-registration:read:all':       ['registry-administrator', 'module-tutor', 'integration-service', 'external-examiner'] as Role[],
  'module-registration:write:own':      ['student'] as Role[],
  'module-registration:write':          ['registry-administrator'] as Role[],
  'catalogue:read':                     ['student', 'module-tutor', 'personal-tutor', 'registry-administrator', 'exam-board-member', 'exam-board-chair', 'integration-service', 'external-examiner'] as Role[],
  'catalogue:write':                    ['registry-administrator', 'tenant-administrator'] as Role[],
  'calendar:read':                      ['student', 'module-tutor', 'registry-administrator', 'integration-service'] as Role[],
  'calendar:write':                     ['registry-administrator', 'tenant-administrator'] as Role[],
  'disability:read:own':                ['student'] as Role[],
  'disability:read':                    ['wellbeing-advisor', 'wellbeing-mental-health-advisor', 'wellbeing-panel-chair', 'wellbeing-auditor', 'dpo', 'registry-administrator'] as Role[],
  'disability:write':                   ['wellbeing-advisor', 'wellbeing-mental-health-advisor', 'registry-administrator'] as Role[],
  'exam-board:write':                   ['registry-administrator'] as Role[],
  'circumstances:read:own':             ['student'] as Role[],
  'circumstances:read':                 ['registry-administrator', 'wellbeing-advisor'] as Role[],
  'circumstances:write':                ['registry-administrator'] as Role[],
  'progression:read':                   ['registry-administrator', 'exam-board-chair', 'exam-board-member'] as Role[],
  'progression:write':                  ['registry-administrator'] as Role[],
  'regulatory:read':                    ['registry-administrator', 'regulatory-officer', 'dpo', 'tenant-administrator', 'system-administrator'] as Role[],
  'regulatory:write':                   ['registry-administrator', 'regulatory-officer', 'dpo', 'tenant-administrator', 'system-administrator'] as Role[],
  'workflow:read':                      ['registry-administrator', 'tenant-administrator'] as Role[],
  'workflow:write':                     ['tenant-administrator'] as Role[],
  'workflow-task:complete':             ['registry-administrator', 'module-tutor', 'personal-tutor', 'wellbeing-advisor', 'exam-board-member', 'exam-board-chair', 'regulatory-officer', 'finance-administrator', 'tenant-administrator'] as Role[],
  'feature-flag:read':                  ['registry-administrator', 'tenant-administrator', 'system-administrator'] as Role[],
  'feature-flag:write':                 ['tenant-administrator', 'system-administrator'] as Role[],
  'feature-flag:govern':                ['system-administrator'] as Role[],
  'environment:read':                   ['registry-administrator', 'tenant-administrator'] as Role[],
  'environment:write':                  ['tenant-administrator'] as Role[],
  'globalisation:read':                 ['registry-administrator', 'tenant-administrator'] as Role[],
  'globalisation:write':                ['tenant-administrator'] as Role[],
  'communications:read':                ['registry-administrator', 'tenant-administrator'] as Role[],
  'communications:write':               ['registry-administrator', 'tenant-administrator'] as Role[],
  'audit-log:read':                     ['dpo', 'system-administrator', 'registry-administrator', 'wellbeing-auditor'] as Role[],
  'retention:enforce':                  ['dpo', 'system-administrator'] as Role[],
  'notifications:read':                 ['student', 'registry-administrator', 'tenant-administrator', 'system-administrator', 'external-examiner'] as Role[],
  'notifications:write':                ['registry-administrator', 'tenant-administrator', 'system-administrator'] as Role[],
  'circumstances:submit':               ['student'] as Role[],
  'engagement:event:read':              ['module-tutor', 'personal-tutor', 'engagement-officer', 'registry-administrator', 'integration-service'] as Role[],
  'engagement:event:write':             ['engagement-officer', 'registry-administrator', 'integration-service'] as Role[],
  'engagement:observation:create':      ['module-tutor', 'engagement-officer', 'registry-administrator', 'integration-service'] as Role[],
  'engagement:observation:correct':     ['module-tutor', 'engagement-officer', 'registry-administrator', 'integration-service'] as Role[],
  'engagement:timeline:read':           ['personal-tutor', 'engagement-officer', 'registry-administrator'] as Role[],
  'engagement:policy:read':             ['engagement-officer', 'registry-administrator', 'tenant-administrator'] as Role[],
  'engagement:policy:manage':           ['tenant-administrator'] as Role[],
  'engagement:evaluation:run':          ['engagement-officer', 'registry-administrator', 'integration-service'] as Role[],
  'engagement:alert:read':              ['personal-tutor', 'engagement-officer', 'registry-administrator'] as Role[],
} as const;

export type Permission = keyof typeof PERMISSION_ROLES;

export function hasPermission(roles: Role[], permission: Permission): boolean {
  const required = PERMISSION_ROLES[permission] as readonly Role[];
  return roles.some((r) => required.includes(r));
}
