import { sql } from 'drizzle-orm';
import type { Db, NewAssessmentComponent, NewIntegrationExchange, NewMark, NewModuleResult } from '@revelation-srs/db';

import { moduleOfferingId } from './curriculum.js';
import { deterministicId } from './ids.js';
import { AUTUMN_MODULES, SPRING_MODULES } from './registrations.js';

// ─── ID helpers ───────────────────────────────────────────────────────────────

export function assessmentComponentId(
  tenantId:        string,
  offeringId:      string,
  componentType:   'coursework' | 'exam',
): string {
  return deterministicId('assessment-component', tenantId, offeringId, componentType);
}

export function markLogicalId(tenantId: string, registrationId: string, componentId: string): string {
  return deterministicId('mark', tenantId, registrationId, componentId);
}

export function moduleResultLogicalId(tenantId: string, registrationId: string): string {
  return deterministicId('module-result', tenantId, registrationId);
}

export function vleRegistrationId(tenantId: string): string {
  return deterministicId('vle-integration-registration', tenantId);
}

// ─── Component generators ─────────────────────────────────────────────────────

export interface OfferingComponentPair {
  coursework: NewAssessmentComponent;
  exam:       NewAssessmentComponent;
}

export function generateComponentsForOffering(
  tenantId:        string,
  offeringId:      string,
  moduleTitle:     string,
  createdAt:       Date = new Date('2025-08-01T00:00:00Z'),
): OfferingComponentPair {
  return {
    coursework: {
      id:                assessmentComponentId(tenantId, offeringId, 'coursework'),
      tenantId,
      moduleOfferingId:  offeringId,
      componentTypeCode: 'coursework',
      title:             `${moduleTitle} — Coursework`,
      weighting:         40,
      createdAt,
      updatedAt:         createdAt,
    },
    exam: {
      id:                assessmentComponentId(tenantId, offeringId, 'exam'),
      tenantId,
      moduleOfferingId:  offeringId,
      componentTypeCode: 'exam',
      title:             `${moduleTitle} — Examination`,
      weighting:         60,
      createdAt,
      updatedAt:         createdAt,
    },
  };
}

// ─── Module offering references ───────────────────────────────────────────────

export interface ModuleOfferingRef {
  offeringId:  string;
  title:       string;
  termCode:    'AUTUMN' | 'SPRING';
}

/**
 * Returns all module offerings (autumn + spring) for the given academic year.
 * Mirrors the offering IDs generated by generateCurriculum.
 */
export function getModuleOfferingsForYear(
  tenantId:     string,
  academicYear: string,
): ModuleOfferingRef[] {
  return [
    ...AUTUMN_MODULES.map(m => ({
      offeringId: moduleOfferingId(tenantId, m.code, academicYear, 'AUTUMN'),
      title:      m.title,
      termCode:   'AUTUMN' as const,
    })),
    ...SPRING_MODULES.map(m => ({
      offeringId: moduleOfferingId(tenantId, m.code, academicYear, 'SPRING'),
      title:      m.title,
      termCode:   'SPRING' as const,
    })),
  ];
}

// ─── Mark generation ──────────────────────────────────────────────────────────

const ACTOR = 'demo-data:assessment-marks';

/**
 * Deterministic raw mark 30–85.
 * ~15% of marks will be below 40 (fail). Distribution is spread across
 * the 30–85 range to give realistic variation.
 */
export function rawMarkForSlot(seq: number, slot: number, componentIdx: number): number {
  return ((seq * 7 + slot * 13 + componentIdx * 3) % 56) + 30;
}

export function generateMark(
  tenantId:       string,
  registrationId: string,
  componentId:    string,
  seq:            number,
  slot:           number,
  componentIdx:   number,
  validFrom:      Date,
): NewMark {
  const raw     = rawMarkForSlot(seq, slot, componentIdx);
  const logicId = markLogicalId(tenantId, registrationId, componentId);

  return {
    versionId:             logicId,
    id:                    logicId,
    tenantId,
    validFrom,
    recordedAt:            validFrom,
    moduleRegistrationId:  registrationId,
    assessmentComponentId: componentId,
    rawMark:               String(raw),
    adjustedMark:          String(raw),
    penaltyApplied:        false,
    attemptNumber:         1,
    locked:                false,
    sourceSystem:          'vle',
    actorId:               ACTOR,
  };
}

// ─── Module result generation ─────────────────────────────────────────────────

export function generateModuleResult(
  tenantId:       string,
  registrationId: string,
  cwMark:         number,
  examMark:       number,
  validFrom:      Date,
): NewModuleResult {
  const aggregate  = Math.round(cwMark * 0.4 + examMark * 0.6);
  const resultCode =
    aggregate >= 40 ? 'pass' :
    aggregate >= 35 ? 'compensated' : 'fail';
  const logicId = moduleResultLogicalId(tenantId, registrationId);

  return {
    versionId:            logicId,
    id:                   logicId,
    tenantId,
    validFrom,
    recordedAt:           validFrom,
    moduleRegistrationId: registrationId,
    aggregateMark:        String(aggregate),
    resultCode,
    locked:               false,
  };
}

// ─── VLE integration helpers ──────────────────────────────────────────────────

export function buildVleRegistration(
  tenantId:              string,
  integrationContractId: string,
): {
  id: string;
  tenantId: string;
  integrationContractId: string;
  integrationCode: string;
  displayName: string;
  contractVersion: string;
  transportCode: string;
  enabled: boolean;
  configuration: Record<string, unknown>;
} {
  return {
    id:                    vleRegistrationId(tenantId),
    tenantId,
    integrationContractId,
    integrationCode:       'demo-vle',
    displayName:           'DEMO - VLE Assessment Results',
    contractVersion:       '1.0',
    transportCode:         'api',
    enabled:               true,
    configuration:         { endpoint: 'https://vle.demo.srs/api/v1/marks' },
  };
}

export function buildVleExchange(
  tenantId:                  string,
  integrationRegistrationId: string,
  registrationId:            string,
  componentId:               string,
  seq:                       number,
  receivedAt:                Date,
): NewIntegrationExchange {
  return {
    tenantId,
    integrationRegistrationId,
    contractId:       'vle-assessment-results.v1',
    directionCode:    'inbound',
    exchangeTypeCode: 'mark-submission',
    idempotencyKey:   `demo:mark:${tenantId}:${registrationId}:${componentId}`,
    statusCode:       seq % 20 === 0 ? 'failed' : 'completed',
    attemptCount:     seq % 20 === 0 ? 3 : 1,
    receivedAt,
    payloadSummary:   { registrationId, componentId },
  };
}

/**
 * Queries the DB for the UUID of the 'vle-assessment-results.v1' integration contract.
 * Returns null if the contract is not seeded (e.g. older migration version).
 */
export async function lookupVleContractId(db: Db): Promise<string | null> {
  const rows = await db.execute(
    sql`SELECT id FROM integration_contract WHERE contract_id = 'vle-assessment-results.v1' LIMIT 1`,
  ) as Array<{ id: string }>;
  return rows[0]?.id ?? null;
}
