export * from './student/created.v1.js';
export * from './student/identity-updated.v1.js';
export * from './student/enrolled.v1.js';
export * from './student/status-changed.v1.js';
export * from './student/disability-declaration-updated.v1.js';
export * from './identity/verification-requested.v1.js';
export * from './identity/verification-completed.v1.js';
export * from './enrolment/fee-liability-generated.v1.js';
export * from './enrolment/downstream-trigger-created.v1.js';
export * from './enrolment/module-registered.v1.js';
export * from './enrolment/module-registration-withdrawn.v1.js';
export * from './enrolment/module-registration-completed.v1.js';
export * from './catalogue/programme-updated.v1.js';
export * from './catalogue/module-updated.v1.js';
export * from './catalogue/module-relationship-updated.v1.js';
export * from './catalogue/learning-outcome-updated.v1.js';
export * from './assessment/mark-received.v1.js';
export * from './assessment/mark-updated.v1.js';
export * from './assessment/module-result-calculated.v1.js';
export * from './assessment/module-result-ratified.v1.js';
export * from './adjustment/approved.v1.js';
export * from './adjustment/distributed.v1.js';
export * from './adjustment/expired.v1.js';
export * from './circumstances/exceptional-circumstances-flagged.v1.js';
export * from './circumstances/exceptional-circumstances-updated.v1.js';
export * from './circumstances/misconduct-outcome-recorded.v1.js';
export * from './governance/exam-board-data-pack-ready.v1.js';
export * from './governance/exam-board-ratified.v1.js';
export * from './governance/record-locked.v1.js';
export * from './governance/record-amended-post-ratification.v1.js';
export * from './progression/decided.v1.js';
export * from './award/conferred.v1.js';
export * from './regulatory/ucas-application-received.v1.js';
export * from './regulatory/ucas-confirmation-sent.v1.js';
export * from './regulatory/hesa-return-generated.v1.js';
export * from './regulatory/hesa-return-submitted.v1.js';
export * from './regulatory/hesa-id-assigned.v1.js';
export * from './regulatory/slc-confirmation-sent.v1.js';
export * from './regulatory/slc-notification-received.v1.js';
export * from './regulatory/ukvi-cas-requested.v1.js';
export * from './regulatory/ukvi-cas-assigned.v1.js';
export * from './regulatory/ukvi-attendance-submitted.v1.js';
export * from './regulatory/ukvi-visa-status-updated.v1.js';
export * from './regulatory/ukvi-compliance-alert-raised.v1.js';
export * from './regulatory/ofs-extract-generated.v1.js';
export * from './governance/exam-entry-submitted.v1.js';
export * from './governance/exam-schedule-received.v1.js';
/** Canonical NATS subject names for all domain events. */
export declare const EVENT_TYPES: {
    readonly STUDENT_CREATED: "srs.student.created";
    readonly STUDENT_IDENTITY_UPDATED: "srs.student.identity-updated";
    readonly STUDENT_ENROLLED: "srs.student.enrolled";
    readonly STUDENT_STATUS_CHANGED: "srs.student.status-changed";
    readonly STUDENT_DISABILITY_DECLARATION_UPDATED: "srs.student.disability-declaration-updated";
    readonly IDENTITY_VERIFICATION_REQUESTED: "srs.identity.verification-requested";
    readonly IDENTITY_VERIFICATION_COMPLETED: "srs.identity.verification-completed";
    readonly ENROLMENT_FEE_LIABILITY_GENERATED: "srs.enrolment.fee-liability-generated";
    readonly ENROLMENT_DOWNSTREAM_TRIGGER_CREATED: "srs.enrolment.downstream-trigger-created";
    readonly ENROLMENT_MODULE_REGISTERED: "srs.enrolment.module-registered";
    readonly ENROLMENT_MODULE_REGISTRATION_WITHDRAWN: "srs.enrolment.module-registration-withdrawn";
    readonly ENROLMENT_MODULE_REGISTRATION_COMPLETED: "srs.enrolment.module-registration-completed";
    readonly CATALOGUE_PROGRAMME_UPDATED: "srs.catalogue.programme-updated";
    readonly CATALOGUE_MODULE_UPDATED: "srs.catalogue.module-updated";
    readonly CATALOGUE_MODULE_RELATIONSHIP_UPDATED: "srs.catalogue.module-relationship-updated";
    readonly CATALOGUE_LEARNING_OUTCOME_UPDATED: "srs.catalogue.learning-outcome-updated";
    readonly ASSESSMENT_MARK_RECEIVED: "srs.assessment.mark-received";
    readonly ASSESSMENT_MARK_UPDATED: "srs.assessment.mark-updated";
    readonly ASSESSMENT_MODULE_RESULT_CALCULATED: "srs.assessment.module-result-calculated";
    readonly ASSESSMENT_MODULE_RESULT_RATIFIED: "srs.assessment.module-result-ratified";
    readonly ADJUSTMENT_APPROVED: "srs.adjustment.approved";
    readonly ADJUSTMENT_DISTRIBUTED: "srs.adjustment.distributed";
    readonly ADJUSTMENT_EXPIRED: "srs.adjustment.expired";
    readonly CIRCUMSTANCES_EC_FLAGGED: "srs.circumstances.exceptional-circumstances-flagged";
    readonly CIRCUMSTANCES_EC_UPDATED: "srs.circumstances.exceptional-circumstances-updated";
    readonly CIRCUMSTANCES_MISCONDUCT_OUTCOME_RECORDED: "srs.circumstances.misconduct-outcome-recorded";
    readonly GOVERNANCE_EXAM_BOARD_DATA_PACK_READY: "srs.governance.exam-board-data-pack-ready";
    readonly GOVERNANCE_EXAM_BOARD_RATIFIED: "srs.governance.exam-board-ratified";
    readonly GOVERNANCE_RECORD_LOCKED: "srs.governance.record-locked";
    readonly GOVERNANCE_RECORD_AMENDED: "srs.governance.record-amended-post-ratification";
    readonly PROGRESSION_DECIDED: "srs.progression.decided";
    readonly AWARD_CONFERRED: "srs.award.conferred";
    readonly REGULATORY_UCAS_APPLICATION_RECEIVED: "srs.regulatory.ucas-application-received";
    readonly REGULATORY_UCAS_CONFIRMATION_SENT: "srs.regulatory.ucas-confirmation-sent";
    readonly REGULATORY_HESA_RETURN_GENERATED: "srs.regulatory.hesa-return-generated";
    readonly REGULATORY_HESA_RETURN_SUBMITTED: "srs.regulatory.hesa-return-submitted";
    readonly REGULATORY_HESA_ID_ASSIGNED: "srs.regulatory.hesa-id-assigned";
    readonly REGULATORY_SLC_CONFIRMATION_SENT: "srs.regulatory.slc-confirmation-sent";
    readonly REGULATORY_SLC_NOTIFICATION_RECEIVED: "srs.regulatory.slc-notification-received";
    readonly REGULATORY_UKVI_CAS_REQUESTED: "srs.regulatory.ukvi-cas-requested";
    readonly REGULATORY_UKVI_CAS_ASSIGNED: "srs.regulatory.ukvi-cas-assigned";
    readonly REGULATORY_UKVI_ATTENDANCE_SUBMITTED: "srs.regulatory.ukvi-attendance-submitted";
    readonly REGULATORY_UKVI_VISA_STATUS_UPDATED: "srs.regulatory.ukvi-visa-status-updated";
    readonly REGULATORY_UKVI_COMPLIANCE_ALERT: "srs.regulatory.ukvi-compliance-alert-raised";
    readonly REGULATORY_OFS_EXTRACT_GENERATED: "srs.regulatory.ofs-extract-generated";
    readonly GOVERNANCE_EXAM_ENTRY_SUBMITTED: "srs.governance.exam-entry-submitted";
    readonly GOVERNANCE_EXAM_SCHEDULE_RECEIVED: "srs.governance.exam-schedule-received";
    readonly WORKFLOW_TASK_ASSIGNED: "srs.workflow.task-assigned";
    readonly WORKFLOW_TASK_COMPLETED: "srs.workflow.task-completed";
    readonly WORKFLOW_TASK_ESCALATED: "srs.workflow.task-escalated";
    readonly WORKFLOW_DECISION_RECORDED: "srs.workflow.decision-recorded";
    readonly WORKFLOW_COMPLETED: "srs.workflow.completed";
};
//# sourceMappingURL=index.d.ts.map